CREATE TABLE my_proj_exp
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_zh      VARCHAR(200) NOT NULL,
    title_en      VARCHAR(200) NOT NULL,
    summary_zh    TEXT         NOT NULL,
    summary_en    TEXT         NOT NULL,
    tech_stack    VARCHAR(500) NOT NULL,
    project_url   VARCHAR(500),
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);